import type { ChurchSpot } from "./types";

export const CHURCH_SPOTS: ChurchSpot[] = [
  {
    id: "font",
    label: "Baptismal font",
    kid: "This is where we were (or will be) washed as God’s child.",
    why: "Baptism is the door of the Church. Water, oil, white garment, candle — we are claimed for the Trinity.",
    doThis: "Dip your fingers and make a Sign of the Cross, remembering your own baptism.",
    x: 14,
    y: 62,
    image: "/images/font.jpg",
  },
  {
    id: "pews",
    label: "Pews",
    kid: "We sit here as a family. Quiet bodies help quiet hearts.",
    why: "The nave is the ship of the Church. Sitting is for listening to the Word; it is not the main posture of worship.",
    doThis: "Practice sitting still for one minute, hands in a lap.",
    x: 48,
    y: 78,
  },
  {
    id: "stations",
    label: "Stations of the Cross",
    kid: "Fourteen pictures of Jesus on the day He died for us.",
    why: "The Via Crucis lets the faithful walk Calvary. In Lent we pray them; all year they teach what love costs.",
    doThis: "On a visit, stop at one station and say: “Jesus, I love you.”",
    x: 8,
    y: 38,
  },
  {
    id: "mary",
    label: "Mary’s place",
    kid: "A statue of Jesus’ mother. We can say hello and ask her to pray.",
    why: "Side altars and shrines are not competing gods. They are family portraits in the Father’s house.",
    doThis: "A small bow, and one Hail Mary if he will stand for it.",
    x: 84,
    y: 48,
  },
  {
    id: "altar",
    label: "Altar",
    kid: "The table of the Last Supper and the place of Jesus’ sacrifice.",
    why: "The altar is both table and Calvary. We bow to it because of the sacrifice offered there.",
    doThis: "A profound bow toward the altar if the tabernacle is elsewhere.",
    x: 50,
    y: 42,
  },
  {
    id: "crucifix",
    label: "Crucifix",
    kid: "Jesus on the Cross. He loves us this much.",
    why: "A crucifix — not an empty cross — keeps the cost of redemption in view. The Mass is this sacrifice made present.",
    doThis: "Look, and whisper “thank you, Jesus.”",
    x: 50,
    y: 18,
  },
  {
    id: "tabernacle",
    label: "Tabernacle",
    kid: "Jesus is home here. See the little red lamp?",
    why: "Reserved Eucharist. Genuflect when the lamp is lit. This is the most important spot in the building.",
    doThis: "Find the lamp. Genuflect on the right knee.",
    x: 58,
    y: 32,
    image: "/images/tabernacle.jpg",
  },
];
