import type { Saint } from "./types";

function s(saint: Saint): Saint {
  return saint;
}

/** More lives for the book — popular patrons, Doctors, American and family saints. */
export const EXTRA_SAINTS: Saint[] = [
  s({
    slug: "anne",
    name: "St. Anne",
    shortName: "Anne",
    title: "Mother of the Blessed Virgin Mary",
    feast: { month: 7, day: 26 },
    born: "Galilee, 1st century B.C. (tradition)",
    died: "1st century (tradition)",
    canonized: "Venerated from the early Church; feast in the West by the 8th century",
    symbols: ["book", "door", "lily", "child Mary"],
    patronages: ["grandparents", "mothers", "housewives", "Canada", "miners", "childless couples"],
    topics: ["family", "grandparents", "Mary", "mothers"],
    kidLine: "Anne is Mary’s mommy — Jesus’ grandma. She taught Mary to love God.",
    summary: "The grandmother of Jesus, honored as the one who raised the woman who said yes.",
    life: "Scripture does not name Mary’s parents. The 2nd-century Protoevangelium of James calls them Joachim and Anne, a long-childless couple given a daughter late. The Church does not treat that book as Gospel, but she has long honored Anne as Mary’s mother. Medieval Europe was full of her shrines. In New France she became the grandmother of a whole people — Sainte-Anne-de-Beaupré still draws pilgrims.",
    stories: [
      {
        title: "The late child",
        text: "Tradition says Anne and Joachim were old and ashamed of empty arms. An angel promised a child who would be blessed among women. Waiting is part of the story grandparents already know.",
      },
    ],
    miracles: [
      {
        title: "Beaupré",
        text: "The Canadian shrine records healings of the crippled and the hopeless, beginning with a 17th-century sailor who helped raise the first chapel and found his own lameness gone.",
      },
    ],
    pathToSainthood:
      "Not a modern canonization. Cultus is ancient in East and West. Pius X approved her as patroness of Canada. The Church’s judgment is the liturgy: we keep her feast with Joachim on July 26.",
    prayer: "St. Anne, grandmother of God-with-us, pray for our house and for every grandparent who still teaches the faith.",
    image: "/images/anne.jpg",
  }),
  s({
    slug: "joachim",
    name: "St. Joachim",
    shortName: "Joachim",
    title: "Father of the Blessed Virgin Mary",
    feast: { month: 7, day: 26 },
    born: "Galilee, 1st century B.C. (tradition)",
    died: "1st century (tradition)",
    canonized: "Venerated with St. Anne from antiquity",
    symbols: ["shepherd’s staff", "doves", "basket"],
    patronages: ["grandfathers", "fathers", "married couples"],
    topics: ["family", "grandparents", "fathers", "Mary"],
    kidLine: "Joachim is Mary’s daddy — Jesus’ grandpa. He waited a long time to be a father.",
    summary: "The quiet grandfather in the Holy Family’s older generation.",
    life: "Paired always with Anne. Tradition paints him as a generous man of Judah whose offering was once refused because he had no child, who went into the wilderness to pray, and who met Anne again at the Golden Gate of Jerusalem with the news of Mary. Whether or not the details are history, the Church keeps a grandfather in the story of the Incarnation.",
    stories: [
      {
        title: "The Golden Gate",
        text: "Art loves the meeting of Anne and Joachim at the gate — two old people who did not stop asking. A father can tell that story without a footnote.",
      },
    ],
    miracles: [
      {
        title: "A long yes",
        text: "The miracle attached to him is not a wonder in a plaza. It is fruitfulness after shame — the kind of answer that takes years.",
      },
    ],
    pathToSainthood: "Cultus with Anne. Their shared feast is July 26 in the General Roman Calendar.",
    prayer: "St. Joachim, pray for fathers who feel late, small, or unseen.",
    image: "/images/anne.jpg",
  }),
  s({
    slug: "andrew",
    name: "St. Andrew the Apostle",
    shortName: "Andrew",
    title: "First-called, apostle",
    feast: { month: 11, day: 30 },
    born: "Bethsaida, 1st century",
    died: "Patras, c. A.D. 60, crucified on an X-shaped cross",
    canonized: "Venerated from the beginning",
    symbols: ["saltire cross", "fish", "net"],
    patronages: ["Scotland", "fishermen", "Russia", "Greece", "singles"],
    topics: ["apostles", "missions", "courage", "invitation"],
    kidLine: "Andrew was Peter’s brother. He met Jesus first, then ran to get Peter.",
    summary: "The apostle who brings other people to Christ, beginning with his own brother.",
    life: "A fisherman of Galilee, first a disciple of John the Baptist. John’s Gospel has him hear “Behold the Lamb,” stay with Jesus, and fetch Simon: “We have found the Messiah.” He appears with the boy who had five loaves. Tradition sends him to Greece; he was bound, not nailed, to an X-shaped cross at Patras so that his witness would last longer.",
    stories: [
      {
        title: "He went and found his brother",
        text: "Evangelization in one sentence. Andrew does not write a treatise. He brings Peter.",
      },
    ],
    miracles: [
      {
        title: "The loaves",
        text: "John 6: Andrew notices the boy with the barley loaves. Small things offered become enough.",
      },
    ],
    pathToSainthood: "Apostolic martyr. His relics went to Constantinople, then to Amalfi; Scotland took him as national patron.",
    prayer: "St. Andrew, first-called, teach us to bring the people we love to Jesus.",
  }),
  s({
    slug: "james-greater",
    name: "St. James the Greater",
    shortName: "James",
    title: "Apostle, son of Zebedee",
    feast: { month: 7, day: 25 },
    born: "Galilee, 1st century",
    died: "Jerusalem, A.D. 44, beheaded by Herod Agrippa",
    canonized: "Venerated from the beginning",
    symbols: ["scallop shell", "staff", "pilgrim hat"],
    patronages: ["pilgrims", "Spain", "laborers", "veterinarians", "horsemen"],
    topics: ["apostles", "pilgrimage", "courage", "martyrs"],
    kidLine: "James walked a long way with Jesus. People still walk a long road to visit him.",
    summary: "One of the three at Tabor and Gethsemane; Spain’s pilgrim saint.",
    life: "Son of Zebedee, brother of John, called from the boat. Jesus named them Boanerges. He wanted seats at the right and left, and was told he would drink the cup. Acts 12: he is the first apostle martyred. Medieval Spain claimed his tomb at Compostela; the Camino still teaches what a long walk can do to a soul.",
    stories: [
      {
        title: "The cup",
        text: "“Can you drink the cup I am to drink?” James said yes. Later Herod’s sword made the yes visible.",
      },
    ],
    miracles: [
      {
        title: "Compostela",
        text: "Pilgrims for a thousand years have arrived at his shrine changed. The Church does not need a laboratory for that miracle.",
      },
    ],
    pathToSainthood: "Apostolic martyr. Patron of Spain; the scallop is the badge of the Camino.",
    prayer: "St. James, pray for everyone on a long road home.",
  }),
  s({
    slug: "thomas-apostle",
    name: "St. Thomas the Apostle",
    shortName: "Thomas",
    title: "Didymus, apostle to India",
    feast: { month: 7, day: 3 },
    born: "Galilee, 1st century",
    died: "Mylapore, India, c. A.D. 72, pierced with a spear (tradition)",
    canonized: "Venerated from the beginning",
    symbols: ["spear", "carpenter’s square", "belt"],
    patronages: ["architects", "builders", "India", "the doubting"],
    topics: ["faith", "doubt", "apostles", "missions"],
    kidLine: "Thomas wanted to see Jesus’ hands. Jesus let him. Then Thomas said, “My Lord and my God.”",
    summary: "The apostle who refused a rumor and then made the highest confession in the Gospel.",
    life: "Called Didymus, “the Twin.” He is willing to die with Jesus (John 11) and honest enough to say he does not know the way (John 14). After the Resurrection he misses the first appearance and will not take the others’ word. Eight days later the Lord offers the wounds. Tradition carries him to India; the St. Thomas Christians of Kerala still claim him.",
    stories: [
      {
        title: "Unless I see",
        text: "Doubt here is not chic unbelief. It is a man who loved too much to be satisfied with a story. Jesus does not scold him off the stage. He invites the hand into the side.",
      },
    ],
    miracles: [
      {
        title: "India",
        text: "Communities on the Malabar coast have kept his memory for centuries. The miracle is a Church where the map said there should not be one.",
      },
    ],
    pathToSainthood: "Apostle and martyr. Feast July 3 (translation of relics); older calendars kept December 21.",
    prayer: "St. Thomas, help us say it when we see Him: my Lord and my God.",
  }),
  s({
    slug: "george",
    name: "St. George",
    shortName: "George",
    title: "Martyr, protector",
    feast: { month: 4, day: 23 },
    born: "Cappadocia or Lydda, c. 275",
    died: "Nicomedia or Lydda, c. 303, under Diocletian",
    canonized: "Venerated from the 4th century; cultus ancient",
    symbols: ["red cross", "white banner", "armor"],
    patronages: ["soldiers", "England", "scouts", "knights", "skin diseases"],
    topics: ["courage", "martyrs", "soldiers", "protection"],
    kidLine: "George was a brave soldier who loved Jesus more than a mean king. He is often painted with a dragon.",
    summary: "A real martyr under Diocletian; the dragon is the later picture of that fight.",
    life: "The oldest witnesses know a soldier-martyr buried at Lydda in Palestine. Acts of his passion grew legendary. The dragon story — a town terrorized, a girl offered, a knight who signs the Cross and saves them — is medieval allegory for baptism crushing evil. England took him as patron in the Crusades. The red cross on white is still his.",
    stories: [
      {
        title: "The dragon",
        text: "Tell a two-year-old: there was something scary. George did not run. He trusted Jesus, and the scary thing lost. That is the whole catechesis.",
      },
    ],
    miracles: [
      {
        title: "Lydda",
        text: "Pilgrims in late antiquity already visited his tomb. Soldiers across East and West have asked his help in the night before a fight.",
      },
    ],
    pathToSainthood:
      "Pre-congregation martyr. Benedict XIV called him a historical saint whose legends need sifting. The Church keeps April 23.",
    prayer: "St. George, pray for the brave, and for anyone who is afraid in the dark.",
    image: "/images/george.jpg",
  }),
  s({
    slug: "lawrence",
    name: "St. Lawrence",
    shortName: "Lawrence",
    title: "Deacon and martyr of Rome",
    feast: { month: 8, day: 10 },
    born: "Spain, c. 225",
    died: "Rome, 258, roasted on a gridiron (tradition)",
    canonized: "Venerated from the beginning in Rome",
    symbols: ["gridiron", "dalmatic", "purse"],
    patronages: ["deacons", "cooks", "comedians", "the poor", "Rome", "librarians"],
    topics: ["the poor", "martyrs", "deacons", "humor"],
    kidLine: "Lawrence took care of poor people. When a mean ruler asked for the Church’s treasure, Lawrence brought the poor.",
    summary: "The archdeacon who showed Rome that the treasure of the Church is her poor.",
    life: "Served Pope Sixtus II. In the Valerian persecution the pope was seized; Lawrence, told to produce the Church’s wealth, gathered the lame, the blind, and the widows. He was killed four days after Sixtus. Tradition says a gridiron; Ambrose and Prudentius already sing him. Rome still stops for him in August heat.",
    stories: [
      {
        title: "These are the treasure",
        text: "A prefect wanted gold. Lawrence brought people. That sentence still indicts every rich diocese.",
      },
      {
        title: "Turn me over",
        text: "The quip on the gridiron — “I’m done on this side” — may be legend. The Church kept it because joy at the end is a kind of miracle.",
      },
    ],
    miracles: [
      {
        title: "The treasure",
        text: "Not a healing. A redefinition: the poor are the patrimony. That conversion of the imagination is why Rome loved him.",
      },
    ],
    pathToSainthood: "Roman martyr of 258. One of the most venerated deacons in the calendar. Feast August 10.",
    prayer: "St. Lawrence, show us where the treasure really is.",
  }),
  s({
    slug: "sebastian",
    name: "St. Sebastian",
    shortName: "Sebastian",
    title: "Martyr, soldier of Rome",
    feast: { month: 1, day: 20 },
    born: "Narbonne or Milan, 3rd century",
    died: "Rome, c. 288, beaten to death after surviving arrows",
    canonized: "Venerated from the 4th century",
    symbols: ["arrows", "column", "armor"],
    patronages: ["athletes", "soldiers", "archers", "plague victims", "police"],
    topics: ["courage", "martyrs", "athletes", "soldiers"],
    kidLine: "Sebastian was a soldier who loved Jesus. Mean men hurt him, but he would not stop being brave.",
    summary: "The Praetorian who encouraged other martyrs and was himself twice condemned.",
    life: "A captain in the imperial guard under Diocletian, he used his post to strengthen imprisoned Christians. Found out, he was shot with arrows and left for dead; Irene of Rome nursed him. He went back to the emperor to rebuke him and was then beaten to death. His relics rest at San Sebastiano on the Appian Way.",
    stories: [
      {
        title: "He went back",
        text: "Surviving the arrows was not the point. Walking back into the palace was. Courage is not one scene.",
      },
    ],
    miracles: [
      {
        title: "Plague saint",
        text: "Medieval cities carried his relics in plague years. Athletes still ask the man who stood at a column for a steady body.",
      },
    ],
    pathToSainthood: "Early Roman martyr. Feast January 20. One of the Fourteen Holy Helpers in later devotion.",
    prayer: "St. Sebastian, pray for strong bodies and stronger hearts.",
  }),
  s({
    slug: "valentine",
    name: "St. Valentine",
    shortName: "Valentine",
    title: "Priest and martyr of Rome",
    feast: { month: 2, day: 14 },
    born: "Italy, 3rd century",
    died: "Rome, c. 269, beheaded",
    canonized: "Venerated from late antiquity",
    symbols: ["roses", "crocus", "heart", "birds"],
    patronages: ["engaged couples", "happy marriages", "beekeepers", "epilepsy", "love"],
    topics: ["marriage", "martyrs", "love"],
    kidLine: "Valentine loved Jesus and helped people get married when it was not allowed. We remember him with notes of love.",
    summary: "A Roman martyr whose name later gathered every story about faithful love.",
    life: "The historical Valentine is thin: a priest or bishop of the 3rd century, buried on the Via Flaminia, feast on February 14. Later legends say he married Christian couples against imperial edict and sent a note “from your Valentine” on the eve of his death. Chaucer and the English then tied the day to spring pairing of birds. The Church keeps a martyr; the culture keeps a card. Both can be baptized.",
    stories: [
      {
        title: "From your Valentine",
        text: "Whether he wrote it or not, the line is true: Christian love has a name, a cost, and a note you can hold.",
      },
    ],
    miracles: [
      {
        title: "Sight restored",
        text: "One legend: he healed the jailer’s blind daughter. Then he wrote her the farewell. Mercy, then a letter.",
      },
    ],
    pathToSainthood:
      "Pre-congregation martyr. Removed from the General Calendar in 1969 for sparse facts, still in the Roman Martyrology on February 14. Local and popular cultus never stopped.",
    prayer: "St. Valentine, pray for our marriage, and for every couple learning how to stay.",
  }),
  s({
    slug: "bernadette",
    name: "St. Bernadette Soubirous",
    shortName: "Bernadette",
    title: "Visionary of Lourdes",
    feast: { month: 4, day: 16 },
    born: "Lourdes, 1844",
    died: "Nevers, 1879",
    canonized: "1933 by Pope Pius XI",
    symbols: ["rosary", "blue sash", "grotto", "candle"],
    patronages: ["the sick", "shepherds", "poverty", "Lourdes", "those ridiculed for piety"],
    topics: ["Mary", "the sick", "humility", "apparitions"],
    kidLine: "Bernadette was a poor girl. Mary came to her at a grotto and asked her to pray and to dig for a spring.",
    summary: "The child of Lourdes who would not embroider the lady, and then hid herself in a convent.",
    life: "The Soubirous family was hungry and lived in a former jail. In 1858 a lady in white appeared eighteen times in the grotto of Massabielle. Bernadette, asthmatic and barely catechized, reported the words “I am the Immaculate Conception” — a title defined only four years earlier, which the girl did not understand. She dug at the lady’s command; a spring rose. She entered the Sisters of Nevers, was treated roughly, and died at 35 of tuberculosis of the bone, saying “pray for me, poor sinner.”",
    stories: [
      {
        title: "The spring",
        text: "A dirty hole in a riverbank. She ate grass and smeared mud on her face as told. The crowd laughed. Then water came. Obedience looked foolish first.",
      },
    ],
    miracles: [
      {
        title: "Lourdes",
        text: "The Church’s medical bureau has documented healings that survive hostile review. They are not the point of the shrine. Conversion is. The water is a sign.",
      },
      {
        title: "Incorruption",
        text: "Her body, exhumed for the cause, was found remarkably preserved. She lies in a glass reliquary at Nevers — not as a spectacle, as a quiet.",
      },
    ],
    pathToSainthood:
      "Died 1879. Beatified 1925, canonized 1933. The Church canonized her life, not the apparitions — though she judged Lourdes worthy of belief.",
    prayer: "St. Bernadette, little and true, pray for the sick and for anyone who is laughed at.",
    image: "/images/bernadette.jpg",
  }),
  s({
    slug: "martha",
    name: "St. Martha of Bethany",
    shortName: "Martha",
    title: "Hostess of the Lord, sister of Mary and Lazarus",
    feast: { month: 7, day: 29 },
    born: "Bethany, 1st century",
    died: "1st century",
    canonized: "Venerated from the beginning",
    symbols: ["keys", "ladle", "dragon (later legend)"],
    patronages: ["cooks", "housewives", "hospitality", "servants", "hoteliers"],
    topics: ["family", "hospitality", "work", "friendship"],
    kidLine: "Martha made dinner for Jesus. She worked hard. Jesus loved her house.",
    summary: "The woman who served, complained, believed, and still kept a place at the table for God.",
    life: "Luke 10: she is anxious about many things while her sister sits. John 11: she runs to meet Jesus before Lazarus’s tomb and makes the same confession as Peter — “I believe you are the Christ.” John 12: she serves again at the supper. The Church needs both sisters. A toddler understands the one who is in the kitchen.",
    stories: [
      {
        title: "The better part",
        text: "Jesus does not hate dinner. He hates the worry that cannot sit down. Martha’s feast day now sits with Mary and Lazarus — the whole house saved.",
      },
    ],
    miracles: [
      {
        title: "Lazarus her brother",
        text: "The great sign in her family is her brother’s return from the tomb. Hospitality, then, is not small. It is the house where God raises the dead.",
      },
    ],
    pathToSainthood: "New Testament saint. Since 2021 the feast is of Martha, Mary, and Lazarus together on July 29.",
    prayer: "St. Martha, pray for everyone cooking while the conversation happens in the other room.",
  }),
  s({
    slug: "perpetua",
    name: "Ss. Perpetua and Felicity",
    shortName: "Perpetua",
    title: "Martyrs of Carthage",
    feast: { month: 3, day: 7 },
    born: "Carthage, late 2nd century",
    died: "Carthage, 203, killed in the arena",
    canonized: "Venerated from the 3rd century; named in the Roman Canon",
    symbols: ["cow", "ladder", "infant"],
    patronages: ["mothers", "expectant mothers", "martyrs", "Carthage"],
    topics: ["mothers", "martyrs", "courage", "friendship"],
    kidLine: "Perpetua and Felicity were mommies who loved Jesus so much they were brave in a hard place.",
    summary: "A noblewoman and her slave, both young mothers, who died together and are named at every Mass in the Canon.",
    life: "Vibia Perpetua, 22, nursing a child, kept a prison diary — one of the earliest writings we have from a Christian woman. Felicity, her slave, gave birth in jail two days before the games. They were thrown to a wild cow, then killed by the sword. Perpetua guided the gladiator’s wavering hand to her own throat. The Church reads them as what baptism costs and what friendship in Christ looks like across class.",
    stories: [
      {
        title: "The ladder",
        text: "Perpetua dreamed a bronze ladder and a dragon under it. She stepped on the dragon’s head and climbed. Baptism as combat, told to a child as: Jesus helps us be brave.",
      },
    ],
    miracles: [
      {
        title: "The diary",
        text: "That a young mother’s own words survive from 203 is itself a mercy. We know their names because they wrote, and because Rome would not forget.",
      },
    ],
    pathToSainthood: "Named in the Roman Canon. Feast March 7. Their passion was public reading in African churches within years of the death.",
    prayer: "Ss. Perpetua and Felicity, pray for mothers, and for friends who will not leave each other.",
  }),
  s({
    slug: "helena",
    name: "St. Helena",
    shortName: "Helena",
    title: "Empress, finder of the True Cross",
    feast: { month: 8, day: 18 },
    born: "Drepanum (perhaps), c. 250",
    died: "Nicomedia, c. 330",
    canonized: "Venerated from late antiquity",
    symbols: ["cross", "crown", "nails"],
    patronages: ["converts", "difficult marriages", "archaeologists", "divorced people"],
    topics: ["conversion", "the Cross", "mothers", "pilgrimage"],
    kidLine: "Helena was an empress who went looking for Jesus’ Cross, and she found it.",
    summary: "Constantine’s mother, a convert who spent her old age digging up the memory of the Passion.",
    life: "Of humble origin, wife then discarded by Constantius Chlorus, mother of Constantine. She converted after her son’s rise. In old age she went to the Holy Land, built churches on the Mount of Olives and at Bethlehem, and — by the tradition Eusebius and later writers keep — recovered the relic of the True Cross. Whether every nail is authentic, the pilgrimage of an empress to the poor places of the Gospel is the point.",
    stories: [
      {
        title: "The three crosses",
        text: "Legend: three crosses found, a dying woman healed when laid on the true one. God identifies His wood by mercy, not by a label.",
      },
    ],
    miracles: [
      {
        title: "The finding",
        text: "The Church keeps the Feast of the Exaltation of the Cross in September in part because of this recovery. Relics can be abused. They can also keep a people from spiritualizing Calvary away.",
      },
    ],
    pathToSainthood: "Cultus ancient, especially in the East. Feast August 18 in the Roman Martyrology.",
    prayer: "St. Helena, teach us to look for the Cross, not to look away.",
  }),
  s({
    slug: "polycarp",
    name: "St. Polycarp of Smyrna",
    shortName: "Polycarp",
    title: "Bishop and martyr, hearer of the apostle John",
    feast: { month: 2, day: 23 },
    born: "c. 69",
    died: "Smyrna, c. 155, burned then stabbed",
    canonized: "Venerated from the 2nd century",
    symbols: ["fire", "dove", "bishop’s staff"],
    patronages: ["earache", "against dysentery"],
    topics: ["martyrs", "apostolic fathers", "courage", "tradition"],
    kidLine: "Polycarp learned about Jesus from someone who knew Jesus. He was brave even when he was old.",
    summary: "The old bishop who would not curse Christ after eighty-six years of service.",
    life: "A disciple of the apostle John, friend of Ignatius of Antioch, teacher of Irenaeus. He held Smyrna in a time of heresy and empire. Arrested as an old man, he was told to say “Caesar is lord.” He answered that he had served Christ eighty-six years. The fire did not at first consume him; a dagger finished it. The Martyrdom of Polycarp is the first full martyr-act outside the New Testament.",
    stories: [
      {
        title: "Eighty-six years",
        text: "“How can I blaspheme my King who saved me?” A sentence a father can memorize for the day the world asks him to be quieter.",
      },
    ],
    miracles: [
      {
        title: "The fire",
        text: "Witnesses said the flames arched around him like a sail. Whether physics or sign, the Church kept the report as the smell of bread baking — a strange mercy in a killing.",
      },
    ],
    pathToSainthood: "Apostolic father and martyr. Feast February 23.",
    prayer: "St. Polycarp, keep us faithful for the long years.",
  }),
  s({
    slug: "justin",
    name: "St. Justin Martyr",
    shortName: "Justin",
    title: "Philosopher and apologist",
    feast: { month: 6, day: 1 },
    born: "Flavia Neapolis (Nablus), c. 100",
    died: "Rome, c. 165, beheaded",
    canonized: "Venerated from the 2nd century",
    symbols: ["scroll", "philosopher’s cloak", "sword"],
    patronages: ["philosophers", "apologists", "speakers"],
    topics: ["conversion", "Scripture", "reason", "martyrs"],
    kidLine: "Justin asked a lot of questions. He found out Jesus is the true answer, and he told other people.",
    summary: "The philosopher who argued that every honest question is already on the way to the Word.",
    life: "A Samaritan-born seeker who tried Stoics, Peripatetics, Pythagoreans, Platonists. An old Christian on a seashore told him to read the prophets. He converted, kept the philosopher’s cloak, and opened a school in Rome. His Apologies describe Sunday Eucharist in the 150s — our earliest full outline of Mass. Denounced by a rival, he was beheaded under Marcus Aurelius.",
    stories: [
      {
        title: "The old man on the shore",
        text: "Arguments had not been enough. A conversation was. Intellectual conversion often looks like hospitality.",
      },
    ],
    miracles: [
      {
        title: "The Apologies",
        text: "That we still know how second-century Christians prayed on Sunday is Justin’s gift. He gave the Church her memory of herself.",
      },
    ],
    pathToSainthood: "Martyr. Feast June 1. Patron of those who think for a living and still have to die for a Name.",
    prayer: "St. Justin, make our questions honest, and our answers brave.",
  }),
  s({
    slug: "leo-great",
    name: "St. Leo the Great",
    shortName: "Leo",
    title: "Pope and Doctor of the Church",
    feast: { month: 11, day: 10 },
    born: "Tuscany, c. 400",
    died: "Rome, 461",
    canonized: "Venerated from his death; Doctor, 1754",
    symbols: ["tiara", "book", "Attila turning away"],
    patronages: ["popes", "spiritual directors", "musicians"],
    topics: ["papacy", "Incarnation", "Doctors", "courage"],
    kidLine: "Leo was a pope who told the truth about Jesus: He is truly God and truly a man. He also talked a fierce king out of wrecking Rome.",
    summary: "The pope who defined Chalcedon in a letter and met Attila at the gates.",
    life: "Elected 440. His Tome to Flavian stated the hypostatic union so clearly the Council of Chalcedon cried “Peter has spoken through Leo.” In 452 he met Attila; the Huns turned back. In 455 he could not stop the Vandals, but he reduced the slaughter. His sermons on the Nativity still teach Christmas: Christian, remember your dignity.",
    stories: [
      {
        title: "Attila",
        text: "A bishop in gold vestments on a road, facing a warlord. Diplomacy as a work of mercy.",
      },
    ],
    miracles: [
      {
        title: "The Tome",
        text: "The miracle is doctrinal: one letter held the center of the faith when the world wanted Jesus to be only God, or only man.",
      },
    ],
    pathToSainthood: "Pope, confessor. Named “the Great.” Declared Doctor of the Church in 1754. Feast November 10.",
    prayer: "St. Leo, keep us from shrinking Christ, and from shrinking our courage.",
  }),
  s({
    slug: "jerome",
    name: "St. Jerome",
    shortName: "Jerome",
    title: "Doctor of the Church, translator of the Vulgate",
    feast: { month: 9, day: 30 },
    born: "Stridon, c. 347",
    died: "Bethlehem, 420",
    canonized: "Venerated from antiquity; Doctor from the start of that list",
    symbols: ["lion", "skull", "cardinal red (later art)", "book"],
    patronages: ["translators", "librarians", "scripture scholars", "archivists"],
    topics: ["Scripture", "Doctors", "penance", "languages"],
    kidLine: "Jerome loved God’s book so much he learned hard languages to write it clearly. A lion is often with him in pictures.",
    summary: "The irascible genius who gave the Latin Church her Bible.",
    life: "Scholar, satirist, desert monk, secretary to Pope Damasus. He learned Hebrew from Jewish teachers and produced the Vulgate, the Latin Bible that formed the West for a millennium. He was difficult, sarcastic, and capable of deep friendship (Paula, Eustochium). He died in Bethlehem near the cave of the Nativity, still arguing and still praying.",
    stories: [
      {
        title: "The lion",
        text: "A legend: he pulled a thorn from a lion’s paw, and the beast stayed. Read it as you like. The real thorn he pulled was ignorance of Scripture.",
      },
    ],
    miracles: [
      {
        title: "The Vulgate",
        text: "A translation that taught Europe to pray. Not flashy. More lasting than a healing at a shrine.",
      },
    ],
    pathToSainthood: "Confessor and Doctor. Feast September 30. One of the four great Latin Doctors.",
    prayer: "St. Jerome, make us students of the Word, even when we are cranky.",
  }),
  s({
    slug: "bernard",
    name: "St. Bernard of Clairvaux",
    shortName: "Bernard",
    title: "Abbot, Doctor mellifluus",
    feast: { month: 8, day: 20 },
    born: "Fontaine-lès-Dijon, 1090",
    died: "Clairvaux, 1153",
    canonized: "1174 by Pope Alexander III",
    symbols: ["white cowl", "bees", "book", "dog"],
    patronages: ["beekeepers", "Gibraltar", "Cistercians", "preachers"],
    topics: ["Mary", "monks", "Doctors", "love"],
    kidLine: "Bernard was a monk who talked about Jesus and Mary with great love. People said his words were like honey.",
    summary: "The Cistercian who pulled Europe by the sleeve back toward the love of God.",
    life: "A Burgundian noble who entered Cîteaux with thirty friends and relatives, then founded Clairvaux. He advised popes, preached the Second Crusade (which failed), and wrote on the Song of Songs as the story of the soul and the Word. His devotion to Mary is the “Our Lady, our mediator” that later centuries would deepen. He could be severe. He was also tender.",
    stories: [
      {
        title: "Lactatio",
        text: "A mystical legend: Mary gives him a drop of milk as wisdom. Too sweet for some. Keep the meaning: all true teaching is received, not invented.",
      },
    ],
    miracles: [
      {
        title: "The honey",
        text: "Called Doctor Mellifluus — the honey-tongued. Crowds wept. The miracle is a preacher who made people want holiness.",
      },
    ],
    pathToSainthood: "Canonized 1174. Named Doctor of the Church in 1830. Feast August 20.",
    prayer: "St. Bernard, teach us to love Mary because we love her Son.",
  }),
  s({
    slug: "albert-the-great",
    name: "St. Albert the Great",
    shortName: "Albert",
    title: "Bishop, Doctor, teacher of Aquinas",
    feast: { month: 11, day: 15 },
    born: "Lauingen, c. 1200",
    died: "Cologne, 1280",
    canonized: "1931 by Pope Pius XI (who also named him Doctor)",
    symbols: ["book", "globe", "Dominican habit"],
    patronages: ["scientists", "philosophers", "students", "naturalists", "Cincinnati"],
    topics: ["science", "study", "Doctors", "Dominicans"],
    kidLine: "Albert loved to look at plants, stars, and animals, and he said: God made these. He was St. Thomas’s teacher.",
    summary: "The bishop who refused the split between the laboratory and the chapel.",
    life: "A German Dominican who taught in Paris and Cologne. He wrote on Aristotle, minerals, animals, the Blessed Sacrament. He recognized Thomas Aquinas’s genius when others called the silent student a “dumb ox.” Late in life he walked to Paris to defend his dead student’s work. He died in Cologne, memory fading, still a Dominican.",
    stories: [
      {
        title: "The dumb ox",
        text: "Classmates mocked Thomas. Albert said: this ox will bellow so loud the world will hear. Teachers exist to see what mockers miss.",
      },
    ],
    miracles: [
      {
        title: "The unity of truth",
        text: "No thunderbolt. A life that treated creation as readable. Catholic science still stands in his shadow.",
      },
    ],
    pathToSainthood: "Beatified 1622, canonized and named Doctor in 1931. Patron of scientists, 1941. Feast November 15.",
    prayer: "St. Albert, bless every child who asks “why,” and every father who does not fake an answer.",
  }),
  s({
    slug: "francis-de-sales",
    name: "St. Francis de Sales",
    shortName: "Francis de Sales",
    title: "Bishop of Geneva, Doctor, gentleman saint",
    feast: { month: 1, day: 24 },
    born: "Thorens, Savoy, 1567",
    died: "Lyons, 1622",
    canonized: "1665 by Pope Alexander VII",
    symbols: ["heart", "crown of thorns", "pen"],
    patronages: ["writers", "journalists", "the deaf", "teachers", "the Catholic press"],
    topics: ["gentleness", "lay holiness", "Doctors", "friendship"],
    kidLine: "Francis was a kind bishop. He said you can be holy at home, not only in a church.",
    summary: "The gentleman who taught that holiness is for kitchens, shops, and marriages.",
    life: "A Savoyard noble, ordained, then missionary in Calvinist Chablais — he slipped pamphlets under doors, the original Catholic journalist. As bishop of Geneva (in exile at Annecy) he directed souls with a courtesy that disarmed. With Jane Frances de Chantal he founded the Visitation. Introduction to the Devout Life is still the book you hand a layperson. He died of a stroke at 55, worn out by letters.",
    stories: [
      {
        title: "The pamphlets",
        text: "He wrote because he could not preach in some towns. Words left on a threshold. Fathers who text a line of faith at lunch are in this line.",
      },
    ],
    miracles: [
      {
        title: "A convert’s patience",
        text: "He won the Chablais back not by a miracle of fire but by years of meek argument. Pius IX named him Doctor in 1877.",
      },
    ],
    pathToSainthood: "Canonized 1665. Doctor of the Church, 1877. Patron of writers and journalists, 1923. Feast January 24.",
    prayer: "St. Francis de Sales, make our words gentle and our homes devout.",
  }),
  s({
    slug: "john-baptist-de-la-salle",
    name: "St. John Baptist de La Salle",
    shortName: "De La Salle",
    title: "Founder of the Christian Brothers",
    feast: { month: 4, day: 7 },
    born: "Reims, 1651",
    died: "Rouen, 1719",
    canonized: "1900 by Pope Leo XIII",
    symbols: ["book", "boys at desks", "star"],
    patronages: ["teachers", "school principals", "educators of the poor"],
    topics: ["teachers", "children", "the poor", "schools"],
    kidLine: "John loved schools. He wanted every child — even poor children — to learn and to know God.",
    summary: "The canon of Reims who gave away a fortune and invented the Catholic school as we know it.",
    life: "Born to privilege, ordained, then captured by the work of training teachers for poor boys. He brought the teachers into his house, resigned his canonry, distributed his wealth in a famine, and founded the Brothers of the Christian Schools. They taught in French, not Latin; in groups, not tutors. He wrote a method, a rule, and a spirituality of the classroom. He died on Good Friday 1719.",
    stories: [
      {
        title: "The fortune",
        text: "Relatives were furious. He let the money go. A school for the poor is always paid for by someone who could have kept it.",
      },
    ],
    miracles: [
      {
        title: "The classroom",
        text: "The miracle is institutional: free schools, trained lay teachers, simultaneous instruction. Modern Catholic education begins here.",
      },
    ],
    pathToSainthood: "Beatified 1888, canonized 1900. Named patron of teachers in 1950. Feast April 7.",
    prayer: "St. John Baptist de La Salle, pray for every tired teacher, including the one at home.",
  }),
  s({
    slug: "camillus",
    name: "St. Camillus de Lellis",
    shortName: "Camillus",
    title: "Founder of the Camillians, giant of the sick",
    feast: { month: 7, day: 14 },
    born: "Bucchianico, 1550",
    died: "Rome, 1614",
    canonized: "1746 by Pope Benedict XIV",
    symbols: ["red cross on a black habit", "sickbed"],
    patronages: ["nurses", "hospitals", "the sick", "doctors"],
    topics: ["the sick", "nurses", "conversion", "mercy"],
    kidLine: "Camillus was very tall and used to be wild. Then he spent his life taking care of sick people.",
    summary: "The converted soldier who taught Europe to put a red cross on the care of the dying.",
    life: "Six-foot-six, a gambler and soldier with a running sore on his leg. Converted at 25, tried the Capuchins, was sent away because of the wound. He served in a Roman hospital, saw the cruelty, and founded a company of men who would tend the sick even in plague ships and battlefields. They wore a red cross — before the Geneva one. He died having spent himself.",
    stories: [
      {
        title: "The wound",
        text: "The thing that kept him out of one order became the door to his vocation. Illness is not always an interruption.",
      },
    ],
    miracles: [
      {
        title: "Plague wards",
        text: "Camillians stayed when others fled. Survivors called it a miracle. It was a vow: to serve Christ in the sick even at the cost of life.",
      },
    ],
    pathToSainthood: "Beatified 1742, canonized 1746. Patron of nurses and hospitals. Feast July 14.",
    prayer: "St. Camillus, stay with us in waiting rooms and at night fevers.",
  }),
  s({
    slug: "john-of-god",
    name: "St. John of God",
    shortName: "John of God",
    title: "Founder of the Hospitallers",
    feast: { month: 3, day: 8 },
    born: "Montemor-o-Novo, Portugal, 1495",
    died: "Granada, 1550",
    canonized: "1690 by Pope Alexander VIII",
    symbols: ["pomegranate", "crown of thorns", "beggar"],
    patronages: ["hospitals", "heart patients", "booksellers", "firefighters", "the mentally ill"],
    topics: ["the sick", "mental illness", "mercy", "hospitals"],
    kidLine: "John took sick people into his house when no one else wanted them.",
    summary: "The wandering soldier who went “mad” for God and invented a hospital that felt like a home.",
    life: "A Portuguese shepherd, then soldier, then peddler of books. A sermon by John of Ávila broke him; he ran the streets of Granada in holy folly and was locked in a psychiatric ward. Ávila visited and told him to turn the madness into work. He rented a house, begged for the sick, carried them on his back. He died of pneumonia after saving patients from a hospital fire, jumping into the cold river.",
    stories: [
      {
        title: "The fire",
        text: "He went in and came out with the sick. Later he would be named a patron of firefighters. Love looks like wet clothes and smoke.",
      },
    ],
    miracles: [
      {
        title: "The house",
        text: "Granada still remembers a hospital born from a breakdown. God uses even the night of the mind.",
      },
    ],
    pathToSainthood: "Canonized 1690. Patron of hospitals and of the dying. Feast March 8.",
    prayer: "St. John of God, carry the ones we cannot carry.",
  }),
  s({
    slug: "gerard-majella",
    name: "St. Gerard Majella",
    shortName: "Gerard",
    title: "Redemptorist lay brother",
    feast: { month: 10, day: 16 },
    born: "Muro Lucano, 1726",
    died: "Caposele, 1755",
    canonized: "1904 by Pope Pius X",
    symbols: ["lily", "crucifix", "letter"],
    patronages: ["expectant mothers", "childbirth", "children", "the falsely accused"],
    topics: ["mothers", "children", "humility", "Redemptorists"],
    kidLine: "Gerard loved mothers and babies. Families still ask him to watch over a baby on the way.",
    summary: "The young tailor-brother who became the patron of those who wait for a child.",
    life: "A frail Italian tailor, refused by Franciscans as too weak, accepted by the Redemptorists as a lay brother. He served as gardener, sacristan, porter. Falsely accused of impurity by a woman who later recanted; he had kept silence as his director ordered. He died of tuberculosis at 29. The patronage of expectant mothers grew from favors reported at his intercession, including a handkerchief he left with a family “for the time of need.”",
    stories: [
      {
        title: "The handkerchief",
        text: "A small cloth, a promise. When the labor went wrong they placed it on the mother, and both lived. From such domestic mercies a patronage is born.",
      },
    ],
    miracles: [
      {
        title: "Childbirth",
        text: "Centuries of mothers have kept his picture in a hospital bag. The Church named him their patron because the favors did not stop.",
      },
    ],
    pathToSainthood: "Beatified 1893, canonized 1904. Feast October 16. A saint who died younger than many new fathers.",
    prayer: "St. Gerard, watch over every mother and the child she carries.",
  }),
  s({
    slug: "peregrine",
    name: "St. Peregrine Laziosi",
    shortName: "Peregrine",
    title: "Servite priest, patron of cancer patients",
    feast: { month: 5, day: 1 },
    born: "Forlì, 1260",
    died: "Forlì, 1345",
    canonized: "1726 by Pope Benedict XIII",
    symbols: ["leg with a sore", "Servite habit"],
    patronages: ["cancer patients", "the sick", "AIDS patients"],
    topics: ["the sick", "conversion", "cancer", "healing"],
    kidLine: "Peregrine was very sick in his leg. He asked Jesus for help, and Jesus made him well. We ask him to pray for people who are very ill.",
    summary: "The political hothead whose own healed cancer made him the friend of the diagnosed.",
    life: "As a young man in Forlì he struck St. Philip Benizi in the face during a riot. Shame converted him; he joined the Servites. For years he stood as a penance and developed varicose veins and a cancerous ulcer of the leg. The night before amputation he dragged himself to the crucifix. He woke healed. He lived another twenty years, dying at 85.",
    stories: [
      {
        title: "The slap",
        text: "He hit a holy man, then followed him. Conversion can start in embarrassment.",
      },
    ],
    miracles: [
      {
        title: "The night before the knife",
        text: "A vision of Christ reaching from the Cross to touch the leg. In the morning the surgeons found nothing to cut. This is why his name is whispered in oncology waiting rooms.",
      },
    ],
    pathToSainthood: "Canonized 1726. Named special patron of cancer patients. Feast May 1.",
    prayer: "St. Peregrine, pray for everyone who has heard a hard diagnosis, and for those who love them.",
  }),
  s({
    slug: "apollonia",
    name: "St. Apollonia",
    shortName: "Apollonia",
    title: "Virgin martyr of Alexandria",
    feast: { month: 2, day: 9 },
    born: "Alexandria, 2nd–3rd century",
    died: "Alexandria, 249, leapt into the fire",
    canonized: "Venerated from the 3rd century",
    symbols: ["pincers", "tooth", "palm"],
    patronages: ["dentists", "toothache", "dental patients"],
    topics: ["martyrs", "courage", "dentists"],
    kidLine: "Apollonia was brave when mean people hurt her teeth. Dentists keep her as a friend.",
    summary: "The deaconess whose broken teeth made her the unlikely patron of a whole profession.",
    life: "During a riot in Alexandria under Decius, an aged Christian woman — Dionysius of Alexandria calls her a deaconess — had her teeth smashed. Threatened with fire unless she repeated impieties, she asked a moment’s pause and leapt into the flames herself. Eusebius kept the letter. The pincers in her icons are not a joke; they are the instrument of her passion.",
    stories: [
      {
        title: "A moment’s pause",
        text: "She was not thrown. She jumped. The Church has always seen that as the freedom of a martyr, not a suicide — she chose the fire rather than the lie.",
      },
    ],
    miracles: [
      {
        title: "Toothache",
        text: "Medieval Christians invoked her at the first pang. Patronage sometimes grows from the wound itself.",
      },
    ],
    pathToSainthood: "Early martyr. Feast February 9. Patroness of dentists — a fact every Catholic child with a loose tooth can be told.",
    prayer: "St. Apollonia, pray for sore mouths, brave dentists, and anyone in sudden pain.",
  }),
  s({
    slug: "florian",
    name: "St. Florian",
    shortName: "Florian",
    title: "Martyr, patron of firefighters",
    feast: { month: 5, day: 4 },
    born: "Cetinium (now in Austria), c. 250",
    died: "Enns river, c. 304, drowned with a stone",
    canonized: "Venerated from late antiquity in Austria and Bavaria",
    symbols: ["bucket", "flag", "burning house", "millstone"],
    patronages: ["firefighters", "brewers", "Austria", "chimney sweeps", "against flood and fire"],
    topics: ["courage", "martyrs", "firefighters", "soldiers"],
    kidLine: "Florian was a soldier who put out fires and loved Jesus. Firefighters ask him to pray.",
    summary: "The officer who would not offer incense, and who still holds a bucket in a thousand firehouse statues.",
    life: "A senior officer of the imperial army in Noricum. When Diocletian’s edicts reached the Danube he refused to sacrifice. He was flogged, then thrown into the Enns with a stone around his neck. Legend adds that he once saved a town with a single bucket of prayer. Austria and Poland took him to heart; immigrant firefighters carried him to American houses.",
    stories: [
      {
        title: "One bucket",
        text: "Whether or not the fire yielded to a pail, the picture is right: one person, on time, with water. That is a fire company.",
      },
    ],
    miracles: [
      {
        title: "The river",
        text: "His body was recovered and buried; a spring rose. Central Europe still walks in his procession on May 4.",
      },
    ],
    pathToSainthood: "Pre-congregation martyr. Feast May 4. Unofficial but universal patron of firefighters.",
    prayer: "St. Florian, guard those who run toward smoke, and keep our home safe in the night.",
  }),
  s({
    slug: "cosmas-damian",
    name: "Ss. Cosmas and Damian",
    shortName: "Cosmas and Damian",
    title: "Unmercenary physicians, martyrs",
    feast: { month: 9, day: 26 },
    born: "Arabia, 3rd century",
    died: "Cyrrhus or Aegea, c. 287",
    canonized: "Venerated from the 4th century; named in the Roman Canon",
    symbols: ["medicine box", "twin portraits", "red robes"],
    patronages: ["physicians", "surgeons", "pharmacists", "twins", "barbers"],
    topics: ["the sick", "mercy", "martyrs", "twins"],
    kidLine: "Cosmas and Damian were twin doctors who did not make people pay. They loved Jesus and helped sick people for free.",
    summary: "The brother-physicians who would not take a fee, and who are named at the heart of the Mass.",
    life: "Twin brothers from Arabia, trained in medicine, they practiced without charge “for the love of Christ” — hence anargyroi, unmercenaries, in the East. Arrested under Diocletian, they survived several attempted executions in the legends before being beheaded. Rome put them in the Canon; a basilica in the Forum still bears their names.",
    stories: [
      {
        title: "No fee",
        text: "The scandal is economic. Healing as gift. A father can say: some things we do because people are ours, not because they can pay.",
      },
    ],
    miracles: [
      {
        title: "The leg of the Ethiopian",
        text: "A famous medieval miracle: they grafted a dead man’s leg onto a cancer patient in the night. Whether surgery or vision, Christian medicine has always been a bit bold.",
      },
    ],
    pathToSainthood: "Named in the Roman Canon. Feast September 26 (West), November 1 (East, with other unmercenaries).",
    prayer: "Ss. Cosmas and Damian, bless doctors, and make our care generous.",
  }),
  s({
    slug: "ivo",
    name: "St. Ivo of Kermartin",
    shortName: "Ivo",
    title: "Advocate of the poor",
    feast: { month: 5, day: 19 },
    born: "Kermartin, Brittany, 1253",
    died: "Louannec, 1303",
    canonized: "1347 by Pope Clement VI",
    symbols: ["lawyer’s cap", "poor clients", "cat (later folk)"],
    patronages: ["lawyers", "judges", "notaries", "abandoned children", "Brittany"],
    topics: ["justice", "the poor", "lawyers", "honesty"],
    kidLine: "Ivo was a lawyer who helped poor people, even when they could not pay.",
    summary: "The parish priest and judge who made “honest lawyer” a possible sentence.",
    life: "A Breton noble, trained in civil and canon law at Paris and Orléans. He served as a diocesan judge, refused bribes, fasted, and represented widows and orphans for nothing. Ordained, he became a parish priest who still pleaded in court. He built a hospital with his own money. Brittany still calls him “sant Erwan.”",
    stories: [
      {
        title: "The widow’s case",
        text: "He would leave the bench to argue for the party who had no counsel. Procedure bent toward the poor, not the other way.",
      },
    ],
    miracles: [
      {
        title: "Canonization in 44 years",
        text: "Miracles at his tomb were numerous enough that a lawyer became a saint while people who had seen him still lived. That itself is evidence.",
      },
    ],
    pathToSainthood: "Canonized 1347. Universal patron of lawyers. Feast May 19.",
    prayer: "St. Ivo, keep every lawyer honest, and every father just in the small cases at home.",
  }),
  s({
    slug: "genesius",
    name: "St. Genesius of Rome",
    shortName: "Genesius",
    title: "Actor and martyr",
    feast: { month: 8, day: 25 },
    born: "Rome, 3rd century",
    died: "Rome, c. 303, beheaded",
    canonized: "Venerated from late antiquity",
    symbols: ["comic mask", "baptismal font on a stage"],
    patronages: ["actors", "comedians", "musicians", "torture victims"],
    topics: ["conversion", "actors", "martyrs", "baptism"],
    kidLine: "Genesius was an actor who made fun of baptism — then he wanted it for real, and he said so.",
    summary: "The mime who mocked the Church, was converted mid-scene, and died for the part he had just received.",
    life: "A Roman actor commissioned to parody Christian baptism before Diocletian. In the middle of the sketch he saw, or believed he saw, angels and a book of his sins washed clean. He stopped the joke and asked for real baptism. The emperor, not amused, had him beaten and beheaded. Theatre people have claimed him ever since.",
    stories: [
      {
        title: "Mid-scene",
        text: "Conversion does not always wait for the end of the show. Sometimes the joke becomes the sacrament.",
      },
    ],
    miracles: [
      {
        title: "The book of sins",
        text: "He saw his own page made white. Whether vision or grace, he would not go back to the script.",
      },
    ],
    pathToSainthood: "Early martyr. Feast August 25. Patron of actors — pray for him before the school play.",
    prayer: "St. Genesius, bless everyone who performs, and make our play true.",
  }),
  s({
    slug: "brigid-kildare",
    name: "St. Brigid of Kildare",
    shortName: "Brigid",
    title: "Abbess, Mary of the Gael",
    feast: { month: 2, day: 1 },
    born: "Faughart, c. 451",
    died: "Kildare, c. 525",
    canonized: "Venerated from the 6th century in Ireland",
    symbols: ["rush cross", "cow", "oak", "lamp"],
    patronages: ["Ireland", "dairymaids", "poets", "midwives", "newborns", "scholars"],
    topics: ["Ireland", "hospitality", "the poor", "nuns"],
    kidLine: "Brigid was a kind Irish girl who shared butter and milk and built a church under an oak.",
    summary: "Ireland’s second patron, whose rush cross still hangs over doors on the eve of spring.",
    life: "Daughter of a chieftain and a slave, she gave away so much food her father despaired. She founded a double monastery at Cill Dara, the church of the oak, and a school of art that would illuminate Gospels. Stories multiply: the cloak that spread over a field, the beer from bathwater for thirsty lepers, the abbess who should have been a bishop in all but name. History is thinner than folklore; holiness is not.",
    stories: [
      {
        title: "The rush cross",
        text: "She wove a cross from floor rushes at a dying chieftain’s bed and taught him Christ with her hands. Irish children still weave them on January 31.",
      },
    ],
    miracles: [
      {
        title: "Butter for the poor",
        text: "Whatever she gave away was found replaced. A household miracle, the right size for a child: God is not outgiven.",
      },
    ],
    pathToSainthood: "Early Irish cultus, twin to Patrick’s. Feast February 1, Imbolc in the old calendar of the land.",
    prayer: "St. Brigid, keep a fire in this house, and a welcome at this door.",
  }),
  s({
    slug: "louis-ix",
    name: "St. Louis IX of France",
    shortName: "Louis",
    title: "King of France, tertiary",
    feast: { month: 8, day: 25 },
    born: "Poissy, 1214",
    died: "Tunis, 1270",
    canonized: "1297 by Pope Boniface VIII",
    symbols: ["crown of thorns", "scepter", "fleur-de-lis"],
    patronages: ["France", "tertiaries", "barbers", "builders", "parenthood"],
    topics: ["fathers", "justice", "kings", "the poor"],
    kidLine: "Louis was a king who prayed, loved his children, and was fair. He built a beautiful chapel for Jesus’ Crown of Thorns.",
    summary: "The king who heard the poor under an oak and raised eleven children toward heaven.",
    life: "Crowned at 12, formed by his mother Blanche. He married Margaret of Provence; they had eleven children. He reformed justice, forbade usury, fed beggars from his table, and built the Sainte-Chapelle for relics of the Passion. He led two Crusades, was captured in Egypt, and died of dysentery near Tunis. Joinville’s Life shows a man who was both king and catechist of his own boys.",
    stories: [
      {
        title: "Under the oak at Vincennes",
        text: "He sat on the ground and heard cases, so the poor could reach him. Authority as availability.",
      },
    ],
    miracles: [
      {
        title: "The Sainte-Chapelle",
        text: "Not a healing — a room of glass that still teaches what a king thought worthy of gold: the Crown of Thorns, not his own.",
      },
    ],
    pathToSainthood: "Canonized 1297, within a generation. Feast August 25. Model of the Christian ruler and of a serious father.",
    prayer: "St. Louis, teach fathers to be just, and to tell their sons the stories that matter.",
  }),
  s({
    slug: "margaret-scotland",
    name: "St. Margaret of Scotland",
    shortName: "Margaret",
    title: "Queen, mother of kings",
    feast: { month: 11, day: 16 },
    born: "Hungary, c. 1045",
    died: "Edinburgh, 1093",
    canonized: "1250 by Pope Innocent IV",
    symbols: ["black cross", "book of Gospels", "crown"],
    patronages: ["Scotland", "large families", "learning", "orphans"],
    topics: ["mothers", "family", "the poor", "queens"],
    kidLine: "Margaret was a queen with many children. She prayed, fed poor people, and taught her family to love God.",
    summary: "The English-Hungarian princess who civilized a court by love and the Mass.",
    life: "Raised in the Hungarian court, shipwrecked onto the Scottish coast, she married King Malcolm III. She bore eight children, reformed court manners, founded churches, ransomed English captives, and served orphans with her own hands. Malcolm, a rough soldier, never learned to read; he kissed her books. She died of grief a few days after he was killed in battle.",
    stories: [
      {
        title: "The king who kissed the book",
        text: "He could not read her Gospel book, so he gold-bound it. Devotion sometimes looks like a husband’s clumsy honor.",
      },
    ],
    miracles: [
      {
        title: "The Gospel book",
        text: "A manuscript of hers, dropped in a river, was found unharmed. It survives in Oxford. A small sign for a woman of the Word.",
      },
    ],
    pathToSainthood: "Canonized 1250. Patroness of Scotland. Feast November 16 (June 10 in some older calendars).",
    prayer: "St. Margaret, pray for large families, and for every mother civilizing a noisy house.",
  }),
  s({
    slug: "margaret-mary",
    name: "St. Margaret Mary Alacoque",
    shortName: "Margaret Mary",
    title: "Apostle of the Sacred Heart",
    feast: { month: 10, day: 16 },
    born: "L’Hautecour, 1647",
    died: "Paray-le-Monial, 1690",
    canonized: "1920 by Pope Benedict XV",
    symbols: ["heart with flames", "Visitation habit"],
    patronages: ["polio sufferers", "devotees of the Sacred Heart", "loss of parents"],
    topics: ["Sacred Heart", "prayer", "reparation", "Eucharist"],
    kidLine: "Jesus showed Margaret Mary His Heart — on fire with love for us. That is why we see pictures of Jesus with a heart.",
    summary: "The Visitation nun who received the Sacred Heart and taught the Church to look at love wounded.",
    life: "A Burgundian girl who lost her father, suffered a long illness, and entered the Visitation at Paray-le-Monial. Between 1673 and 1675 she received revelations of Christ’s Heart, asking for a feast, for First Friday Communion, and for a holy hour of reparation. She was mocked in her own convent until St. Claude de la Colombière, her Jesuit confessor, discerned the grace. She died saying “I shall die happy, because I have the Heart of Jesus.”",
    stories: [
      {
        title: "The holy hour",
        text: "He asked her to keep Him company in the Garden for an hour. A toddler can sit with a candle. That is already the devotion.",
      },
    ],
    miracles: [
      {
        title: "The feast",
        text: "The Sacred Heart feast is now universal. A hidden nun changed the calendar. That is a miracle of obedience more than of fire.",
      },
    ],
    pathToSainthood: "Beatified 1864, canonized 1920. Feast October 16. The Sacred Heart devotion she carried is now ordinary Catholic air.",
    prayer: "St. Margaret Mary, make our family’s heart a little like His.",
  }),
  s({
    slug: "catherine-laboure",
    name: "St. Catherine Labouré",
    shortName: "Catherine Labouré",
    title: "Daughter of Charity, seer of the Miraculous Medal",
    feast: { month: 11, day: 28 },
    born: "Fain-lès-Moutiers, 1806",
    died: "Paris, 1876",
    canonized: "1947 by Pope Pius XII",
    symbols: ["miraculous medal", "cornette", "rays from hands"],
    patronages: ["the elderly", "miraculous medal", "catechists"],
    topics: ["Mary", "humility", "medal", "the poor"],
    kidLine: "Mary showed Catherine a medal. On it Mary’s hands pour light. People still wear it.",
    summary: "The silent sister who kept a secret for forty years while the medal went around the world.",
    life: "A Burgundy farmer’s daughter, she saw a vision of St. Vincent as a child and joined the Daughters of Charity in Paris. In 1830, in the chapel on the Rue du Bac, the Blessed Virgin showed her the design of a medal: Mary standing on the globe, rays from her fingers, the prayer “O Mary, conceived without sin, pray for us who have recourse to thee.” Catherine told only her confessor. She spent the rest of her life answering the door and caring for old men, unrecognized. The medal spread by millions.",
    stories: [
      {
        title: "The chair",
        text: "In one apparition Mary sat in the chapel and Catherine rested her hands on Mary’s knees, like a child. That is the tone of this devotion: near, not theatrical.",
      },
    ],
    miracles: [
      {
        title: "The medal",
        text: "Conversions and healings attached to it from the 1830s. The Church does not treat the medal as magic. It is a sacramental: a visible plea.",
      },
    ],
    pathToSainthood:
      "Her identity was revealed only after death. Beatified 1933, canonized 1947. Body incorrupt at the Rue du Bac. Feast November 28.",
    prayer: "St. Catherine, keep us small, and keep this medal from becoming a charm.",
  }),
  s({
    slug: "louis-montfort",
    name: "St. Louis de Montfort",
    shortName: "Louis de Montfort",
    title: "Missionary, apostle of Marian consecration",
    feast: { month: 4, day: 28 },
    born: "Montfort-sur-Meu, 1673",
    died: "Saint-Laurent-sur-Sèvre, 1716",
    canonized: "1947 by Pope Pius XII",
    symbols: ["book", "rosary", "walking staff"],
    patronages: ["preachers", "the Rosary", "consecrated persons"],
    topics: ["Mary", "Rosary", "missions", "consecration"],
    kidLine: "Louis told people: belong to Jesus with Mary’s help. He loved the Rosary.",
    summary: "The ragged missionary who taught that giving oneself to Mary is the short road to Christ.",
    life: "A Breton priest who walked western France preaching parish missions, often forbidden pulpits, sometimes beaten. He wrote True Devotion to Mary — the manuscript was lost for over a century — and the Secret of the Rosary. He founded the Company of Mary and the Daughters of Wisdom. He died at 43, worn out. John Paul II took his motto Totus Tuus from him.",
    stories: [
      {
        title: "The lost book",
        text: "True Devotion lay hidden in a chest through the Revolution and was found in 1842. Some seeds need winter.",
      },
    ],
    miracles: [
      {
        title: "Totus Tuus",
        text: "A pope’s whole pontificate traced to a skinny Breton’s little treatise. Influence is a slow miracle.",
      },
    ],
    pathToSainthood: "Beatified 1888, canonized 1947. Feast April 28. Patron of those who make or renew Marian consecration.",
    prayer: "St. Louis, let our family belong to Jesus through Mary, without fuss.",
  }),
  s({
    slug: "john-xxiii",
    name: "St. John XXIII",
    shortName: "John XXIII",
    title: "Pope of the Council, Good Pope John",
    feast: { month: 10, day: 11 },
    born: "Sotto il Monte, 1881",
    died: "Vatican, 1963",
    canonized: "2014 by Pope Francis",
    symbols: ["papal tiara", "open window", "smile"],
    patronages: ["papal delegates", "Christian unity", "the Second Vatican Council"],
    topics: ["papacy", "peace", "humor", "Council"],
    kidLine: "Pope John was a round, kind pope who opened a big Church meeting so people could love Jesus better.",
    summary: "The peasant pope who called Vatican II and made the papacy feel like a grandfather.",
    life: "Angelo Roncalli, fourth of thirteen children, diplomat in Bulgaria, Turkey, and France, Patriarch of Venice, elected at 76 as a “caretaker.” He called the Second Vatican Council, wrote Pacem in Terris, visited prisoners and hospitals, and kept a humor that disarmed. He died of stomach cancer during the Council, beloved even by people who did not love Rome.",
    stories: [
      {
        title: "A moon over the square",
        text: "On the night before the Council opened he spoke from the window to a crowd: “Go home and give your children a kiss.” A pontificate in one domestic sentence.",
      },
    ],
    miracles: [
      {
        title: "The opening",
        text: "He said he wanted to open the windows. Whether one likes every draft, the courage to call a council as an old man is a kind of wonder.",
      },
    ],
    pathToSainthood: "Beatified 2000 by John Paul II, canonized 2014 with John Paul II. Feast October 11, opening day of Vatican II.",
    prayer: "St. John XXIII, give us grandfatherly courage and a peaceful house.",
  }),
  s({
    slug: "josemaria",
    name: "St. Josemaría Escrivá",
    shortName: "Josemaría",
    title: "Founder of Opus Dei",
    feast: { month: 6, day: 26 },
    born: "Barbastro, 1902",
    died: "Rome, 1975",
    canonized: "2002 by Pope John Paul II",
    symbols: ["Mass kit", "rose", "ordinary desk"],
    patronages: ["diabetics", "ordinary work"],
    topics: ["work", "lay holiness", "everyday", "Mass"],
    kidLine: "Josemaría said that doing ordinary things — work, dishes, play — can be a way to love God.",
    summary: "The priest who taught that a desk and a kitchen are altars if the intention is love.",
    life: "A Spanish priest who, in 1928, saw a mission to remind ordinary Christians that they are called to holiness without leaving the world. He founded Opus Dei, suffered the Civil War, moved to Rome, and wrote The Way — short, sharp points for people who have jobs. Critics found the movement too tight; the Church judged the founder’s holiness. He died in his workroom.",
    stories: [
      {
        title: "The chocolate",
        text: "He taught children (and adults) to offer little things: a sweet not taken, a job finished well. The little way, in a suit.",
      },
    ],
    miracles: [
      {
        title: "A surgeon’s hands",
        text: "The miracle for canonization involved a medical healing after prayer for his intercession. The deeper claim is a million sanctified workdays.",
      },
    ],
    pathToSainthood: "Beatified 1992, canonized 2002. Feast June 26. A saint for commutes and inboxes.",
    prayer: "St. Josemaría, bless this ordinary day, and the work in it.",
  }),
  s({
    slug: "newman",
    name: "St. John Henry Newman",
    shortName: "Newman",
    title: "Cardinal, convert, Doctor of the Church",
    feast: { month: 10, day: 9 },
    born: "London, 1801",
    died: "Edgbaston, 1890",
    canonized: "2019 by Pope Francis; named Doctor of the Church by Pope Leo XIV, 1 November 2025",
    symbols: ["cardinal’s hat", "book", "Oratorian collar"],
    patronages: ["converts", "students", "essayists"],
    topics: ["conversion", "conscience", "study", "England"],
    kidLine: "John Henry loved truth so much he left a church he knew to come into the Catholic Church, even though it cost him friends.",
    summary: "The Oxford man who followed an argument into Rome and taught the West about conscience and development.",
    life: "Anglican priest, leader of the Oxford Movement, received into the Church in 1845 at great personal cost. Founded the Oratory in Birmingham, wrote Apologia pro Vita Sua, The Idea of a University, and the Essay on Development. Made cardinal by Leo XIII. A prose master who never became a bishop, which may have been a mercy. Heart Speaks to Heart was his motto.",
    stories: [
      {
        title: "Lead, Kindly Light",
        text: "A poem written in illness at sea, years before his conversion: “one step enough for me.” A father’s prayer when the map is short.",
      },
    ],
    miracles: [
      {
        title: "The deacon in America",
        text: "His canonization miracle was the healing of a pregnant American deacon’s wife from a grave diagnosis. The Englishman’s reach is now ordinary.",
      },
    ],
    pathToSainthood:
      "Beatified 2010 by Benedict XVI at Birmingham, canonized 2019. In 2025 Pope Leo XIV named him a Doctor of the Church. Feast October 9.",
    prayer: "St. John Henry, keep our consciences tender and our minds honest.",
  }),
  s({
    slug: "charbel",
    name: "St. Charbel Makhlouf",
    shortName: "Charbel",
    title: "Maronite hermit of Lebanon",
    feast: { month: 7, day: 24 },
    born: "Bekaa Kafra, 1828",
    died: "Annaya, 1898",
    canonized: "1977 by Pope Paul VI",
    symbols: ["hood", "light from the tomb", "cedars"],
    patronages: ["Lebanon", "hermits", "those who suffer in silence"],
    topics: ["prayer", "silence", "the sick", "monks"],
    kidLine: "Charbel was a quiet monk on a mountain. He loved to pray. People still ask him to pray when someone is sick.",
    summary: "The hermit whose silence outlived empires, and whose tomb still draws the sick.",
    life: "A Maronite shepherd boy who became a monk at Annaya, then a hermit in a hillside cell. He celebrated Mass with intense recollection, lived on almost nothing, and died of a stroke on Christmas Eve after a liturgy. Lights were seen at his tomb; his body was found intact and exuding moisture. He has become a sign of Lebanese holiness beyond all factions.",
    stories: [
      {
        title: "The mountain",
        text: "He chose a cell over a pulpit. In a loud age, that choice is already a sermon.",
      },
    ],
    miracles: [
      {
        title: "Healings at Annaya",
        text: "Thousands of favors, including documented medical cases, are attached to his intercession. Oil, light, and silence — the style of his wonders matches his life.",
      },
    ],
    pathToSainthood: "Beatified 1965, canonized 1977. Feast July 24 (third Sunday of July in the Maronite calendar).",
    prayer: "St. Charbel, teach us to be quiet enough to pray.",
  }),
  s({
    slug: "damien-molokai",
    name: "St. Damien of Molokai",
    shortName: "Damien",
    title: "Apostle to the lepers",
    feast: { month: 5, day: 10 },
    born: "Tremelo, Belgium, 1840",
    died: "Kalaupapa, Hawaii, 1889",
    canonized: "2009 by Pope Benedict XVI",
    symbols: ["leprosy bandages", "SS.CC. habit", "Hawaiian chapel"],
    patronages: ["people with leprosy", "outcasts", "Hawaii", "those with HIV"],
    topics: ["the sick", "outcasts", "missions", "courage"],
    kidLine: "Damien went to live with people nobody else would live with, so they would not be alone.",
    summary: "The Belgian priest who became Hawaiian, then a patient among his patients.",
    life: "Jozef De Veuster of the Congregation of the Sacred Hearts volunteered for the isolated leprosy settlement on Molokai in 1873. He built churches, houses, and coffins; dressed wounds; and wrote letters that shamed a comfortable world. After sixteen years he announced at Mass: “We lepers.” He died of the disease in 1889. Robert Louis Stevenson defended him against a smearing Protestant critic in a famous open letter.",
    stories: [
      {
        title: "We lepers",
        text: "The grammar of the Incarnation. He would not speak of “you” any longer.",
      },
    ],
    miracles: [
      {
        title: "A life as argument",
        text: "The miracle the Church needed was already public: a man who stayed. Formal healings later confirmed what Hawaii already knew.",
      },
    ],
    pathToSainthood: "Beatified 1995, canonized 2009. Feast May 10. Patron of those the healthy prefer not to see.",
    prayer: "St. Damien, send us toward the people who sit alone.",
  }),
  s({
    slug: "katharine-drexel",
    name: "St. Katharine Drexel",
    shortName: "Katharine",
    title: "Foundress of the Sisters of the Blessed Sacrament",
    feast: { month: 3, day: 3 },
    born: "Philadelphia, 1858",
    died: "Bensalem, 1955",
    canonized: "2000 by Pope John Paul II",
    symbols: ["lilies", "schoolhouse", "tabernacle"],
    patronages: ["racial justice", "philanthropists", "orphans"],
    topics: ["America", "the poor", "Eucharist", "justice"],
    kidLine: "Katharine was a rich American girl who spent her money building schools for children who were treated unfairly.",
    summary: "The heiress who spent a fortune on Black and Native American missions, and herself on the tabernacle.",
    life: "Daughter of a Philadelphia banker, she inherited millions and, after Leo XIII challenged her to become a missionary, founded a congregation dedicated to Native and Black Americans. She built schools and Xavier University in New Orleans — the first Catholic HBCU. She took the Jim Crow fight personally, suing when the law blocked her work. After a heart attack in 1935 she spent twenty years in adoration. She died at 96.",
    stories: [
      {
        title: "The pope’s question",
        text: "She told Leo XIII how hard it was to find missionaries. He asked: “Why not become one yourself?” Vocations sometimes arrive as a dare.",
      },
    ],
    miracles: [
      {
        title: "Deafness healed",
        text: "The canonization miracle was the restoration of a boy’s hearing after prayer for her intercession — a fitting sign for a woman who spent her life helping people be heard.",
      },
    ],
    pathToSainthood: "Beatified 1988, canonized 2000. Feast March 3. Second American-born saint.",
    prayer: "St. Katharine, make our generosity concrete, and our adoration long.",
  }),
  s({
    slug: "andre-bessette",
    name: "St. André Bessette",
    shortName: "André",
    title: "Brother of Holy Cross, porter of St. Joseph",
    feast: { month: 1, day: 6 },
    born: "Saint-Grégoire, Quebec, 1845",
    died: "Montreal, 1937",
    canonized: "2010 by Pope Benedict XVI",
    symbols: ["oil of St. Joseph", "Oratory dome", "porter’s keys"],
    patronages: ["the sick", "Canada", "porters", "the poorly educated"],
    topics: ["Joseph", "the sick", "humility", "Canada"],
    kidLine: "André was a small, sickly doorman. He loved St. Joseph. A great church grew from his little door.",
    summary: "The illiterate porter whose devotion to St. Joseph built an oratory on a mountain.",
    life: "Orphaned, frail, barely able to read, he was accepted by the Holy Cross Brothers with reluctance and posted as porter at Notre-Dame College in Montreal: “I was at the door for forty years.” He rubbed the sick with oil from a lamp before St. Joseph’s statue and told them to pray to Joseph, not to him. Crowds came. He collected nickels for a shrine on Mount Royal; the vast Oratory stands there now. He died at 91.",
    stories: [
      {
        title: "The door",
        text: "A whole theology of work: the lowest job, done as if Joseph himself had assigned it.",
      },
    ],
    miracles: [
      {
        title: "Oil and oakum",
        text: "Thousands of healings were attributed to Joseph through André’s hands. The Church required, and found, a miracle for canonization; Montreal had already stopped counting.",
      },
    ],
    pathToSainthood: "Beatified 1982, canonized 2010. Feast January 6 (January 7 in Canada). First male Canadian-born saint.",
    prayer: "St. André, open doors, and send us to St. Joseph when we are little and tired.",
  }),
  s({
    slug: "isaac-jogues",
    name: "St. Isaac Jogues",
    shortName: "Isaac Jogues",
    title: "Jesuit martyr of North America",
    feast: { month: 10, day: 19 },
    born: "Orléans, 1607",
    died: "Ossernenon (Auriesville, New York), 1646",
    canonized: "1930 by Pope Pius XI",
    symbols: ["mangled hands", "Jesuit cassock", "canoe"],
    patronages: ["America", "missionaries", "the Americas"],
    topics: ["missions", "martyrs", "America", "courage"],
    kidLine: "Isaac came across the ocean to tell people about Jesus. It was very hard. He still went back.",
    summary: "The priest who lost his fingers to torture, received permission to say Mass anyway, and returned to the people who had maimed him.",
    life: "A French Jesuit sent to the Huron missions. Captured by Mohawks in 1642, he was tortured; they chewed off his fingers. He escaped to France, where Urban VIII allowed him to celebrate Mass with mutilated hands — “it would be unjust for a martyr of Christ not to drink the Blood of Christ.” He went back as a peace envoy and was tomahawked at Ossernenon. He is one of the North American Martyrs.",
    stories: [
      {
        title: "The permission",
        text: "The Church changed a rubric for a pair of ruined hands. Sacraments are for the wounded.",
      },
    ],
    miracles: [
      {
        title: "The return",
        text: "Going back is the miracle. Conversion of the Mohawk — including Kateri’s people — grew from such returns.",
      },
    ],
    pathToSainthood: "Canonized 1930 with his companions. Feast October 19 (September 26 in Canada). Patron of the missions of North America.",
    prayer: "St. Isaac, for every hard place we would rather not enter again.",
  }),
  s({
    slug: "charles-lwanga",
    name: "St. Charles Lwanga",
    shortName: "Charles Lwanga",
    title: "Martyr of Uganda, patron of youth",
    feast: { month: 6, day: 3 },
    born: "Bulimu, Buganda, c. 1860",
    died: "Namugongo, 1886, burned",
    canonized: "1964 by Pope Paul VI",
    symbols: ["flame", "white robe", "palm"],
    patronages: ["youth", "converts", "torture victims", "African Catholic youth"],
    topics: ["youth", "courage", "purity", "Africa"],
    kidLine: "Charles was a young man who protected boys in the king’s house and would not stop following Jesus, even in the fire.",
    summary: "The page who baptized his boys on the road to the pyre, and smiled.",
    life: "Chief of the royal pages at the court of Mwanga II. After the killing of the Anglican bishop Hannington and of Joseph Mukasa, Charles baptized the younger catechumens in secret. Arrested for refusing the king’s sexual demands and for their Christianity, they were marched to Namugongo. Charles was burned on Ascension Thursday, 1886. Twenty-two Catholic martyrs — and Anglican companions — made Uganda a Christian nation by blood.",
    stories: [
      {
        title: "On the road",
        text: "He baptized the youngest with a little instruction and a lot of courage. Catechesis can be brief when the fire is near.",
      },
    ],
    miracles: [
      {
        title: "Uganda",
        text: "Within a century the country that killed them became one of the most Christian on the continent. Tertullian’s sentence, made visible.",
      },
    ],
    pathToSainthood: "Beatified 1920, canonized 1964 by Paul VI in Rome, with African bishops present. Feast June 3.",
    prayer: "St. Charles Lwanga, guard the young, and make them brave and clean.",
  }),
  s({
    slug: "john-neumann",
    name: "St. John Neumann",
    shortName: "John Neumann",
    title: "Bishop of Philadelphia, Redemptorist",
    feast: { month: 1, day: 5 },
    born: "Prachatice, Bohemia, 1811",
    died: "Philadelphia, 1860",
    canonized: "1977 by Pope Paul VI",
    symbols: ["bishop’s staff", "schoolhouse", "small stature"],
    patronages: ["Catholic schools", "immigrants", "sick children", "Philadelphia"],
    topics: ["America", "immigrants", "schools", "bishops"],
    kidLine: "John came from far away to be a priest in America. He built schools so children could learn about God.",
    summary: "The tiny immigrant bishop who put a parish school system under the feet of a new country.",
    life: "Too many priests in Bohemia, not enough in America. He arrived in New York in 1836, was ordained, rode circuits in upstate woods, joined the Redemptorists, and at 41 became bishop of Philadelphia. He organized the first diocesan school system in the United States, learned languages to hear confessions of immigrants, and collapsed of a stroke on a street at 48. People had thought him unimpressive. Rome did not.",
    stories: [
      {
        title: "Forty hours",
        text: "He spread the Forty Hours Devotion so the Eucharist would not be lonely in a busy city. A bishop’s job is to keep the lamp lit.",
      },
    ],
    miracles: [
      {
        title: "The schools",
        text: "Institutional miracle: Catholic schooling as a system, not a hobby. Healings later served the cause; the schools served the children.",
      },
    ],
    pathToSainthood: "Beatified 1963, canonized 1977 — first American male saint. Feast January 5.",
    prayer: "St. John Neumann, bless immigrant families and the schools that catch their children.",
  }),
  s({
    slug: "solanus-casey",
    name: "Bl. Solanus Casey",
    shortName: "Solanus",
    title: "Capuchin porter of Detroit",
    feast: { month: 7, day: 30 },
    born: "Oak Grove, Wisconsin, 1870",
    died: "Detroit, 1957",
    canonized: "Beatified 2017; canonization cause open",
    symbols: ["violin", "Capuchin habit", "soup kitchen"],
    patronages: ["Detroit", "the sick", "those who fail exams"],
    topics: ["humility", "the sick", "America", "gratitude"],
    kidLine: "Solanus was a kind American brother who played the violin and listened to people at the door.",
    summary: "The simplex priest who could not preach public sermons, so he blessed a city from a doorway.",
    life: "Barney Casey, Irish-American logger and streetcar conductor, struggled through seminary Latin and was ordained a “simplex” priest — able to say Mass, not to preach or hear confessions. The Capuchins made him porter in Yonkers, then Detroit. Crowds came for blessings, healings, and the sentence he stamped on every request: “Give thanks beforehand.” He founded a soup kitchen in the Depression. He died in 1957; Detroit lined the streets.",
    stories: [
      {
        title: "Give thanks beforehand",
        text: "He asked people to thank God before the answer. That is faith as manners.",
      },
    ],
    miracles: [
      {
        title: "The doorkeeper’s favors",
        text: "A woman with a skin disease healed overnight was among the favors studied for beatification. Detroit’s memory is longer than the dossier.",
      },
    ],
    pathToSainthood:
      "Declared Venerable 1995, beatified 2017 in Detroit. Not yet canonized — the Church still walks with him. He is in this book because American families already ask his prayers.",
    prayer: "Bl. Solanus, we thank God beforehand for whatever He will do in this house.",
  }),
  s({
    slug: "philip",
    name: "St. Philip the Apostle",
    shortName: "Philip",
    title: "Apostle",
    feast: { month: 5, day: 3 },
    born: "Bethsaida, 1st century",
    died: "Hierapolis, 1st century, crucified (tradition)",
    canonized: "Venerated from the beginning",
    symbols: ["loaves", "cross", "dragon (later)"],
    patronages: ["hatters", "pastry chefs", "Luxembourg"],
    topics: ["apostles", "invitation", "Eucharist"],
    kidLine: "Philip told his friend Nathanael: “Come and see.” That is still how we share Jesus.",
    summary: "The apostle of the invitation, who never stopped bringing people into the conversation.",
    life: "From Bethsaida, like Peter and Andrew. Jesus finds him and says “Follow me.” Philip finds Nathanael. At the feeding he does the math (“two hundred denarii would not buy enough”). At the Last Supper he asks to see the Father, and Jesus says “He who has seen me has seen the Father.” Tradition sends him to Phrygia.",
    stories: [
      {
        title: "Come and see",
        text: "The whole missionary method of a family: not a lecture. An invitation to look.",
      },
    ],
    miracles: [
      {
        title: "The bread",
        text: "He saw the problem (no food). Jesus made it his problem, then more than solved it. Apostles do arithmetic; God does the rest.",
      },
    ],
    pathToSainthood: "Apostle. Feast May 3 with St. James the Less.",
    prayer: "St. Philip, teach us to say come and see, especially to our own.",
  }),
  s({
    slug: "barnabas",
    name: "St. Barnabas",
    shortName: "Barnabas",
    title: "Apostle, son of encouragement",
    feast: { month: 6, day: 11 },
    born: "Cyprus, 1st century",
    died: "Salamis, Cyprus, 1st century, stoned (tradition)",
    canonized: "Venerated from the beginning",
    symbols: ["olive branch", "Gospel of Matthew", "stones"],
    patronages: ["Cyprus", "peacemakers", "encouragers"],
    topics: ["encouragement", "missions", "friendship", "apostles"],
    kidLine: "Barnabas’s name means “son of encouragement.” He was Paul’s friend and helped people be brave.",
    summary: "The Levite who vouched for Paul when no one else would, and who lived up to his nickname.",
    life: "A Cypriot Levite named Joseph, nicknamed Barnabas by the apostles. He sold a field. He introduced Saul to the Jerusalem church. He fetched Paul to Antioch; together they took the first missionary journey. They split over John Mark — Barnabas taking the younger man who had failed. Tradition has him martyred in Cyprus. Every parish needs a Barnabas more than it needs a genius.",
    stories: [
      {
        title: "He took Mark",
        text: "Paul wanted reliability. Barnabas wanted a second chance. The Church kept both men, and Mark later wrote a Gospel. Encouragement is apostolic.",
      },
    ],
    miracles: [
      {
        title: "Antioch",
        text: "Acts 11: he saw the grace of God and was glad. Discernment that rejoices is a quiet wonder.",
      },
    ],
    pathToSainthood: "Called apostle in Acts 14. Feast June 11.",
    prayer: "St. Barnabas, make this house a place of encouragement.",
  }),
  s({
    slug: "brendan",
    name: "St. Brendan the Navigator",
    shortName: "Brendan",
    title: "Abbot of Clonfert",
    feast: { month: 5, day: 16 },
    born: "County Kerry, c. 484",
    died: "Annaghdown, c. 577",
    canonized: "Venerated from the early Irish church",
    symbols: ["coracle", "whale", "monks at oars"],
    patronages: ["sailors", "travelers", "whales", "boatmen"],
    topics: ["Ireland", "travelers", "monks", "adventure"],
    kidLine: "Brendan was a monk who sailed far in a little boat to find a holy island, and to find God.",
    summary: "The Irish abbot whose voyage became the Middle Ages’ favorite adventure of grace.",
    life: "Founder of Clonfert, teacher of monks. The Navigatio Brendani tells of a seven-year voyage in a leather boat to the “Isle of the Promised Saints,” with islands of birds, a sea of crystal, and a whale mistaken for land. History cannot chart it; sailors still claim him. Some read Newfoundland in the story. Read it first as a picture of the soul: we leave, we are fed, we return.",
    stories: [
      {
        title: "The whale",
        text: "They said Mass on a “island” that moved. Creation is not a stage set. It is alive, and God is in the motion.",
      },
    ],
    miracles: [
      {
        title: "The voyage",
        text: "That Irish monks crossed terrible water in skin boats is not legend. That God met them is the claim of the story.",
      },
    ],
    pathToSainthood: "Early Irish cultus. Feast May 16. Patron of sailors — a good friend on any trip.",
    prayer: "St. Brendan, go with us when we leave home, even for a small errand.",
  }),
  s({
    slug: "bede",
    name: "St. Bede the Venerable",
    shortName: "Bede",
    title: "Monk of Jarrow, Doctor of the Church",
    feast: { month: 5, day: 25 },
    born: "Northumbria, c. 673",
    died: "Jarrow, 735",
    canonized: "Named Doctor in 1899 by Leo XIII; cultus ancient in England",
    symbols: ["book", "quill", "monk’s cowl"],
    patronages: ["historians", "English writers", "scholars"],
    topics: ["study", "England", "Doctors", "monks"],
    kidLine: "Bede was a monk who wrote down the stories of his people so no one would forget what God had done.",
    summary: "The quiet Englishman who gave a nation its memory and died singing the doxology.",
    life: "Given to the monastery of Wearmouth-Jarrow as a child, he almost never left. He wrote the Ecclesiastical History of the English People — still the reason we know Augustine of Canterbury, Cuthbert, and the coming of the faith to the Angles. He wrote on time, Scripture, grammar. On the eve of the Ascension he finished a translation of John, distributed his little treasures, and died saying “Glory be to the Father.”",
    stories: [
      {
        title: "The last sentence",
        text: "He wanted to finish the Gospel before vespers. Work, done for God, may be completed on a deathbed. That is a happy death.",
      },
    ],
    miracles: [
      {
        title: "A history that held",
        text: "Without Bede, early English Christianity is scraps. God sometimes saves a people by giving them a librarian.",
      },
    ],
    pathToSainthood: "Called Venerable in his own generation. Declared Doctor of the Church in 1899. Feast May 25.",
    prayer: "St. Bede, bless the stories we tell our children, and make them true.",
  }),
  s({
    slug: "elmo",
    name: "St. Erasmus of Formia (Elmo)",
    shortName: "Elmo",
    title: "Bishop and martyr, one of the Fourteen Holy Helpers",
    feast: { month: 6, day: 2 },
    born: "Antioch, 3rd century",
    died: "Formia, c. 303",
    canonized: "Venerated from the early Middle Ages",
    symbols: ["windlass", "ship", "blue light"],
    patronages: ["sailors", "stomach pain", "colic", "childbirth", "explosives workers"],
    topics: ["sailors", "the sick", "martyrs", "protection"],
    kidLine: "Sailors call him Elmo. When they see a little blue light on the mast in a storm, they remember he is near.",
    summary: "The martyr whose windlass became a sailor’s light in the rigging.",
    life: "A bishop who fled Diocletian’s persecution, preached in Italy, and was tortured — later legend adds a windlass and his entrails, which is why he is invoked for abdominal pain. Sailors named St. Elmo’s fire, the blue glow of static on masts, after him: a sign that the saint is watching in the storm. Formia keeps his relics.",
    stories: [
      {
        title: "The blue light",
        text: "A physicist will say corona discharge. A sailor in a gale will say a name. Both can be true. Sacramentals have always borrowed nature.",
      },
    ],
    miracles: [
      {
        title: "The Helpers",
        text: "Medieval Christians grouped fourteen saints for desperate needs. Elmo was the one you asked when the sea or the gut turned on you.",
      },
    ],
    pathToSainthood: "Early martyr, later Holy Helper. Feast June 2.",
    prayer: "St. Elmo, in every storm — weather, stomach, or soul — stay with us.",
  }),
  s({
    slug: "barbara",
    name: "St. Barbara",
    shortName: "Barbara",
    title: "Virgin martyr, Holy Helper",
    feast: { month: 12, day: 4 },
    born: "Nicomedia or Heliopolis, 3rd century (legend)",
    died: "3rd century, beheaded by her father (legend)",
    canonized: "Cultus medieval; removed from General Calendar 1969, still in the Martyrology",
    symbols: ["tower", "chalice", "lightning", "three windows"],
    patronages: ["miners", "artillerymen", "lightning", "architects", "fireworks", "a happy death"],
    topics: ["martyrs", "protection", "the dying", "courage"],
    kidLine: "Barbara’s father locked her in a tower. She still chose Jesus. People ask her to pray in storms and in mines.",
    summary: "A martyr whose tower and three windows taught the Trinity to people who worked with fire and stone.",
    life: "The historical dossier is thin, which is why her feast left the universal calendar. The legend is thick and loved: a pagan father, a tower, three windows she ordered for the Trinity, baptism, flight, betrayal, lightning upon the father who killed her. Miners, gunners, and anyone who works with sudden fire took her as patron. The Church still permits her cult where it is alive.",
    stories: [
      {
        title: "Three windows",
        text: "She wanted light in threes. Architecture as creed. A child can count to three and hear the Father, the Son, and the Spirit.",
      },
    ],
    miracles: [
      {
        title: "Lightning",
        text: "Her father struck by fire from heaven is the legend’s justice. Better to ask her now to keep fire in its place.",
      },
    ],
    pathToSainthood:
      "Legendary passion, real cultus. In the Martyrology on December 4. Included here because families still search “patron of lightning / miners / a happy death.”",
    prayer: "St. Barbara, keep sudden dangers far, and keep us ready for a holy death.",
  }),
  s({
    slug: "roch",
    name: "St. Roch",
    shortName: "Roch",
    title: "Pilgrim of Montpellier",
    feast: { month: 8, day: 16 },
    born: "Montpellier, c. 1295",
    died: "Montpellier, c. 1327",
    canonized: "Popular canonization in the plague centuries; confirmed in cultus",
    symbols: ["pilgrim staff", "dog with bread", "plague sore on the thigh"],
    patronages: ["plague", "dogs", "invalids", "knee problems", "surgeons"],
    topics: ["the sick", "animals", "pilgrimage", "the poor"],
    kidLine: "Roch was sick on a road. A dog brought him bread. He is a friend of dogs and of people who feel poorly.",
    summary: "The pilgrim who nursed plague victims, caught it, and was fed by a dog in the woods.",
    life: "A French noble who gave away his goods and walked as a pilgrim, nursing the plague-stricken in Italy. He fell ill, dragged himself to a forest, and was supplied with bread by a hunting dog. Healed, he went home, was taken for a spy, and died in prison unrecognized. When plague returned to Europe, his pictures went up over doors: a man lifting his tunic to show the sore, a dog at his feet.",
    stories: [
      {
        title: "The dog",
        text: "Tell it straight: God used a dog. Animals in hagiography are not cute extras. They are providence with fur.",
      },
    ],
    miracles: [
      {
        title: "Plague crosses",
        text: "Cities that invoked him recorded cessations. Correlation is not cause; a people on their knees is already a healing of a kind.",
      },
    ],
    pathToSainthood: "Cultus confirmed by the later Middle Ages. Feast August 16. Patron of dogs — and of anyone waiting for a recovery.",
    prayer: "St. Roch, pray for the sick, and for the animals that keep us company.",
  }),
];
