/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BedtimeRouteImport } from './routes/bedtime'
import { Route as ChurchRouteImport } from './routes/church'
import { Route as MassRouteImport } from './routes/mass'
import { Route as PrayRouteImport } from './routes/pray'
import { Route as SaintsRouteImport } from './routes/saints'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as SaintsSlugRouteImport } from './routes/saints.$slug'
import { Route as StoriesIdRouteImport } from './routes/stories.$id'
import { Route as TeachIdRouteImport } from './routes/teach.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BedtimeRoute = BedtimeRouteImport.update({
  id: '/bedtime',
  path: '/bedtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchRoute = ChurchRouteImport.update({
  id: '/church',
  path: '/church',
  getParentRoute: () => rootRouteImport,
} as any)
const MassRoute = MassRouteImport.update({
  id: '/mass',
  path: '/mass',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayRoute = PrayRouteImport.update({
  id: '/pray',
  path: '/pray',
  getParentRoute: () => rootRouteImport,
} as any)
const SaintsRoute = SaintsRouteImport.update({
  id: '/saints',
  path: '/saints',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const SaintsSlugRoute = SaintsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SaintsRoute,
} as any)
const StoriesIdRoute = StoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoriesRoute,
} as any)
const TeachIdRoute = TeachIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bedtime': typeof BedtimeRoute
  '/church': typeof ChurchRoute
  '/mass': typeof MassRoute
  '/pray': typeof PrayRoute
  '/saints': typeof SaintsRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/teach': typeof TeachRouteWithChildren
  '/saints/$slug': typeof SaintsSlugRoute
  '/stories/$id': typeof StoriesIdRoute
  '/teach/$id': typeof TeachIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bedtime': typeof BedtimeRoute
  '/church': typeof ChurchRoute
  '/mass': typeof MassRoute
  '/pray': typeof PrayRoute
  '/saints': typeof SaintsRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/teach': typeof TeachRouteWithChildren
  '/saints/$slug': typeof SaintsSlugRoute
  '/stories/$id': typeof StoriesIdRoute
  '/teach/$id': typeof TeachIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bedtime': typeof BedtimeRoute
  '/church': typeof ChurchRoute
  '/mass': typeof MassRoute
  '/pray': typeof PrayRoute
  '/saints': typeof SaintsRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/teach': typeof TeachRouteWithChildren
  '/saints/$slug': typeof SaintsSlugRoute
  '/stories/$id': typeof StoriesIdRoute
  '/teach/$id': typeof TeachIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bedtime'
    | '/church'
    | '/mass'
    | '/pray'
    | '/saints'
    | '/stories'
    | '/teach'
    | '/saints/$slug'
    | '/stories/$id'
    | '/teach/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bedtime'
    | '/church'
    | '/mass'
    | '/pray'
    | '/saints'
    | '/stories'
    | '/teach'
    | '/saints/$slug'
    | '/stories/$id'
    | '/teach/$id'
  id:
    | '__root__'
    | '/'
    | '/bedtime'
    | '/church'
    | '/mass'
    | '/pray'
    | '/saints'
    | '/stories'
    | '/teach'
    | '/saints/$slug'
    | '/stories/$id'
    | '/teach/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BedtimeRoute: typeof BedtimeRoute
  ChurchRoute: typeof ChurchRoute
  MassRoute: typeof MassRoute
  PrayRoute: typeof PrayRoute
  SaintsRoute: typeof SaintsRouteWithChildren
  StoriesRoute: typeof StoriesRouteWithChildren
  TeachRoute: typeof TeachRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedtime': {
      id: '/bedtime'
      path: '/bedtime'
      fullPath: '/bedtime'
      preLoaderRoute: typeof BedtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/church': {
      id: '/church'
      path: '/church'
      fullPath: '/church'
      preLoaderRoute: typeof ChurchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mass': {
      id: '/mass'
      path: '/mass'
      fullPath: '/mass'
      preLoaderRoute: typeof MassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pray': {
      id: '/pray'
      path: '/pray'
      fullPath: '/pray'
      preLoaderRoute: typeof PrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saints': {
      id: '/saints'
      path: '/saints'
      fullPath: '/saints'
      preLoaderRoute: typeof SaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saints/$slug': {
      id: '/saints/$slug'
      path: '/$slug'
      fullPath: '/saints/$slug'
      preLoaderRoute: typeof SaintsSlugRouteImport
      parentRoute: typeof SaintsRoute
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/teach/$id': {
      id: '/teach/$id'
      path: '/$id'
      fullPath: '/teach/$id'
      preLoaderRoute: typeof TeachIdRouteImport
      parentRoute: typeof TeachRoute
    }
  }
}

interface SaintsRouteChildren {
  SaintsSlugRoute: typeof SaintsSlugRoute
}

const SaintsRouteChildren: SaintsRouteChildren = {
  SaintsSlugRoute: SaintsSlugRoute,
}

const SaintsRouteWithChildren =
  SaintsRoute._addFileChildren(SaintsRouteChildren)

interface StoriesRouteChildren {
  StoriesIdRoute: typeof StoriesIdRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesIdRoute: StoriesIdRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

interface TeachRouteChildren {
  TeachIdRoute: typeof TeachIdRoute
}

const TeachRouteChildren: TeachRouteChildren = {
  TeachIdRoute: TeachIdRoute,
}

const TeachRouteWithChildren = TeachRoute._addFileChildren(TeachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BedtimeRoute: BedtimeRoute,
  ChurchRoute: ChurchRoute,
  MassRoute: MassRoute,
  PrayRoute: PrayRoute,
  SaintsRoute: SaintsRouteWithChildren,
  StoriesRoute: StoriesRouteWithChildren,
  TeachRoute: TeachRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
